package(default_visibility = ["//visibility:public"])

cc_library(
    name = "freestanding",
    includes = ["."],
    hdrs = [
        "assert.h",
        "float.h",
        "iso646.h",
        "limits.h",
        "stdalign.h",
        "stdarg.h",
        "stdbool.h",
        "stddef.h",
        "stdint.h",
        "stdnoreturn.h",
    ],
)
