#ifndef LOCAL_GOOGLE_HOME_CFRANTZ_OPENTITAN_SPX_SW_DEVICE_EXAMPLES_MLDSA_FW_RAND_H_
#define LOCAL_GOOGLE_HOME_CFRANTZ_OPENTITAN_SPX_SW_DEVICE_EXAMPLES_MLDSA_FW_RAND_H_
#include <stdint.h>
#include <stddef.h>

void OQS_randombytes(uint8_t *output, size_t len);


#endif  // LOCAL_GOOGLE_HOME_CFRANTZ_OPENTITAN_SPX_SW_DEVICE_EXAMPLES_MLDSA_FW_RAND_H_
